### World ###
WORLD_SIZE_Y = 10
WORLD_SIZE_X = 10
SHIPS = [5,4,3,3,2]

### Benchmark ###
BENCHMARK = 10

### ML ###
TRAINING_ROUNDS = 1_000_000
BATCH_SIZR = 10

#for evaluvation during training
EVAL_DURING_RUNTIME = False
EVAL_ROUNDS = 10
EVAL_EVERY = 100_000


### Monte Carlo ###
MONTE_CARLO_SAMPLES = 1000
MONTE_CARLO_PRIORITY = 5
HEAT_MAP = True
